version: '3.8'

services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
    container_name: node-app
    expose:
      - '4000'
    ports:
      - '4000:4000'
    command: npm run build && npm start